# permissions for end users to view objstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: objstore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helm-operator
    app.kubernetes.io/part-of: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: objstore-viewer-role
rules:
- apiGroups:
  - demo.lil.harsh.com
  resources:
  - objstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.lil.harsh.com
  resources:
  - objstores/status
  verbs:
  - get
